### ISSUE TITLE
Сайтнинг умумий кўринишни тузиш

### ISSUE THREAD

**Issue by uzbekkorea** [uzbekkorea/uzbekkorea.github.io#1]
## Дизайн
- Лого
- Бош меню
- Слайдер (Корея табиат ва шаҳар расмлари)
- Янгилклар (блог сифатида)

## Бош менюдаги саҳифалар
- Бош саҳифа
- Фойдали маълумотлар
- Янгиликлар
- Корея ҳақида
   - Жойлашув ва иқлими
   - Тарихи
   - Иқтисоди
   - Маданяти
   - Транспорт
   - Спорт
- Турар жойлар
- Озиқ-овқат
- Савдо-сотиқ

**Comment by jsr1611** [comment]
Assalomu alaykum Elmurod aka!
Loyihaga men ham hissa qo`shishni xohlar edim, qanday hissa qo`shsam bo`ladi?

**Comment by uzbekkorea** [comment]
@jsr1611 
Va alaykum assalom, 
Fork -> Pull Request qilib contribution qilsangiz bo'ladi.
Hozircha, contributor listga qo'shib qo'ydim fork qilmasdan ham qilsangiz bo'ladi.

**Comment by bit-scientist** [comment]
Saytni ham lotin-o'zbek, ham kiril-o'zbek tillarida yuritish qanchalik o'rinli bo'ladi? Shu ikkala yozuvdan bir-biriga o'giradigan biror tayyor kutubxona bormi?
